project:
  type: default
  output-dir: outputs

format:
  html:
    theme: default
    toc: true
    fig-width: 8
    fig-height: 6
    lightbox: true
  pdf:
    documentclass: article
    geometry: margin=1in
  docx:
    reference-doc: journal-template.docx

execute:
  echo: false
  warning: false
  message: false
  cache: true

bibliography: references.bib